name: nuevosol
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_crashlytics: ^5.0.0
  injectable: ^2.5.1
  animated_custom_dropdown: ^3.1.1
  fl_chart: ^0.71.0
  connectivity_plus: ^6.1.5
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^4.0.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.0
  package_info_plus: ^8.3.1
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  file_picker: ^10.3.1
  url_launcher: ^6.3.1
  mobile_scanner: ^3.5.2
  dotted_line: ^3.2.3
  simple_barcode_scanner: ^0.3.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.0.0-0.0.dev
  injectable_generator: ^2.6.2

  pubspec_dependency_sorter: ^1.0.5


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
