// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE8Psg9BCHtXbBuglobaI75Sv03owUvVg',
    appId: '1:247437191888:web:817da0b220cd76d486ccd5',
    messagingSenderId: '247437191888',
    projectId: 'nuevosol-6b4e0',
    authDomain: 'nuevosol-6b4e0.firebaseapp.com',
    storageBucket: 'nuevosol-6b4e0.firebasestorage.app',
    measurementId: 'G-SQRSMMTL5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gXxE0VYSMjkjmnE3RbLkDDlbEaDxSYI',
    appId: '1:247437191888:android:45577e7a958290d886ccd5',
    messagingSenderId: '247437191888',
    projectId: 'nuevosol-6b4e0',
    storageBucket: 'nuevosol-6b4e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJPab3DBczztz_GHTcQz1Hs7SXLA9Gqk',
    appId: '1:247437191888:ios:b89c0d4b3a312d8c86ccd5',
    messagingSenderId: '247437191888',
    projectId: 'nuevosol-6b4e0',
    storageBucket: 'nuevosol-6b4e0.firebasestorage.app',
    iosBundleId: 'com.example.nuevosol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFJPab3DBczztz_GHTcQz1Hs7SXLA9Gqk',
    appId: '1:247437191888:ios:b89c0d4b3a312d8c86ccd5',
    messagingSenderId: '247437191888',
    projectId: 'nuevosol-6b4e0',
    storageBucket: 'nuevosol-6b4e0.firebasestorage.app',
    iosBundleId: 'com.example.nuevosol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE8Psg9BCHtXbBuglobaI75Sv03owUvVg',
    appId: '1:247437191888:web:ccdc6821b05f1ea486ccd5',
    messagingSenderId: '247437191888',
    projectId: 'nuevosol-6b4e0',
    authDomain: 'nuevosol-6b4e0.firebaseapp.com',
    storageBucket: 'nuevosol-6b4e0.firebasestorage.app',
    measurementId: 'G-BEB5H3C9TK',
  );

}