// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'bom_items.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$BomItemsImpl _$$BomItemsImplFromJson(Map<String, dynamic> json) =>
    _$BomItemsImpl(
      name: json['name'] as String?,
      owner: json['owner'] as String?,
      creation: json['creation'] as String?,
      modified: json['modified'] as String?,
      modifiedBy: json['modified_by'] as String?,
      docstatus: (json['docstatus'] as num?)?.toInt(),
      idx: (json['idx'] as num?)?.toInt(),
      parent: json['parent'] as String?,
      parentfield: json['parentfield'] as String?,
      parenttype: json['parenttype'] as String?,
      itemCode: json['item_code'] as String?,
      itemName: json['item_name'] as String?,
      operation: json['operation'] as String?,
      customComponentScanning: json['custom_component_scanning'] as String?,
      customPackageQty: (json['custom_package_qty'] as num?)?.toDouble(),
      customNoOfScan: (json['custom_no_of_scan'] as num?)?.toDouble(),
      doNotExplode: (json['do_not_explode'] as num?)?.toInt(),
      bomNo: json['bom_no'] as String?,
      sourceWarehouse: json['source_warehouse'] as String?,
      allowAlternativeItem: (json['allow_alternative_item'] as num?)?.toInt(),
      isStockItem: (json['is_stock_item'] as num?)?.toInt(),
      description: json['description'] as String?,
      image: json['image'] as String?,
      qty: (json['qty'] as num?)?.toDouble(),
      uom: json['uom'] as String?,
      stockQty: (json['stock_qty'] as num?)?.toDouble(),
      stockUom: json['stock_uom'] as String?,
      conversionFactor: (json['conversion_factor'] as num?)?.toDouble(),
      rate: (json['rate'] as num?)?.toDouble(),
      baseRate: (json['base_rate'] as num?)?.toDouble(),
      amount: (json['amount'] as num?)?.toDouble(),
      baseAmount: (json['base_amount'] as num?)?.toDouble(),
      qtyConsumedPerUnit: (json['qty_consumed_per_unit'] as num?)?.toDouble(),
      hasVariants: (json['has_variants'] as num?)?.toInt(),
      includeItemInManufacturing:
          (json['include_item_in_manufacturing'] as num?)?.toInt(),
      originalItem: json['original_item'] as String?,
      sourcedBySupplier: (json['sourced_by_supplier'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$BomItemsImplToJson(_$BomItemsImpl instance) =>
    <String, dynamic>{
      'name': instance.name,
      'owner': instance.owner,
      'creation': instance.creation,
      'modified': instance.modified,
      'modified_by': instance.modifiedBy,
      'docstatus': instance.docstatus,
      'idx': instance.idx,
      'parent': instance.parent,
      'parentfield': instance.parentfield,
      'parenttype': instance.parenttype,
      'item_code': instance.itemCode,
      'item_name': instance.itemName,
      'operation': instance.operation,
      'custom_component_scanning': instance.customComponentScanning,
      'custom_package_qty': instance.customPackageQty,
      'custom_no_of_scan': instance.customNoOfScan,
      'do_not_explode': instance.doNotExplode,
      'bom_no': instance.bomNo,
      'source_warehouse': instance.sourceWarehouse,
      'allow_alternative_item': instance.allowAlternativeItem,
      'is_stock_item': instance.isStockItem,
      'description': instance.description,
      'image': instance.image,
      'qty': instance.qty,
      'uom': instance.uom,
      'stock_qty': instance.stockQty,
      'stock_uom': instance.stockUom,
      'conversion_factor': instance.conversionFactor,
      'rate': instance.rate,
      'base_rate': instance.baseRate,
      'amount': instance.amount,
      'base_amount': instance.baseAmount,
      'qty_consumed_per_unit': instance.qtyConsumedPerUnit,
      'has_variants': instance.hasVariants,
      'include_item_in_manufacturing': instance.includeItemInManufacturing,
      'original_item': instance.originalItem,
      'sourced_by_supplier': instance.sourcedBySupplier,
    };
